\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		R1  | g1 | a1 | d1 | d1 |

		% hay una uncion...
		g1 | a1 | fs1:m | b1:m |
		g1 | a1 | d1 | d1 |

		% hay una uncion...
		g1 | a1 | fs1:m | b1:m |
		g1 | a1 | d1 | d1:7 |

		% mi espiritu y mi alma...
		g1 | a1 | fs1:m | b1:m |
		g1 | a1 | d1 | d1:7 |

		% mi espiritu y mi alma...
		g1 | a1 | fs1:m | b1:m |
		g1 | a1 | d1 | d1 |
	}
