\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		R1  | a1 | b1 | e1 | e1 |

		% hay una uncion...
		a1 | b1 | gs1:m | cs1:m |
		a1 | b1 | e1 | e1 |

		% hay una uncion...
		a1 | b1 | gs1:m | cs1:m |
		a1 | b1 | e1 | e1:7 |

		% mi espiritu y mi alma...
		a1 | b1 | gs1:m | cs1:m |
		a1 | b1 | e1 | e1:7 |

		% mi espiritu y mi alma...
		a1 | b1 | gs1:m | cs1:m |
		a1 | b1 | e1 | e1 |
	}
